# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Small%20Slant&t=Site%20Settings
#
#     _____ __        ____    __  __  _
#    / __(_) /____   / __/__ / /_/ /_(_)__  ___ ____
#   _\ \/ / __/ -_) _\ \/ -_) __/ __/ / _ \/ _ `(_-<
#  /___/_/\__/\__/ /___/\__/\__/\__/_/_//_/\_, /___/
#                                         /___/
#
remote_theme: uol-library/jekyll-theme-uol
title: Digital Library Infrastructure Project
url: https://uol-dlip.github.io
repository: uol-dlip/uol-dlip.github.io
author:
  name: Research Management and Libraries
  email: emu@library.leeds.ac.uk
description: >
  Improving search, access and use of the University’s digital rare and
  unique items (Cultural Collections) to enhance learning, research and 
  collaboration.

google_analytics: "GTM-WJPZM2T" # set to Google Tag manager ID

# contact information
contact:
  organisation: Leeds University Library
  # Address
  address:
    street: Woodhouse Lane
    locality: Leeds
    region: West Yorkshire
    postcode: LS2 9JT
    country: UK
  telephone: +44 0113 243 1751
  email: emu@library.leeds.ac.uk

  # Social media links
  social_links:
    # facebook: uol
    # instagram: uol
    # linkedin: uol
    # medium: uol
    # twitter: uol
    # weibo: uol

    # either a youtube user
    # youtube: uol
    
    # or a youtube channel
    # youtube_channel: 
    # youtube_channel_name: 

# Blog settings
paginate: 10
paginate_path: "/blog/page:num/"
show_excerpts: true
# Date format - this is overridden in post-list-item.html
date_format: "%A %-d %b, %Y"
permalink: pretty

theme: 
exclude:
  - README.md
  - LICENSE

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
